[2022-04-13 22:21:39,400] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.ingest manual__2022-04-13T21:15:36.839665+00:00 [queued]>
[2022-04-13 22:21:39,422] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAG.ingest manual__2022-04-13T21:15:36.839665+00:00 [queued]>
[2022-04-13 22:21:39,422] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 22:21:39,423] {taskinstance.py:1239} INFO - Starting attempt 3 of 3
[2022-04-13 22:21:39,423] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-13 22:21:39,446] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): ingest> on 2022-04-13 21:15:36.839665+00:00
[2022-04-13 22:21:39,451] {standard_task_runner.py:52} INFO - Started process 8497 to run task
[2022-04-13 22:21:39,460] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDAG', 'ingest', 'manual__2022-04-13T21:15:36.839665+00:00', '--job-id', '1410', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpncdl2fbc', '--error-file', '/tmp/tmpaxazk6d3']
[2022-04-13 22:21:39,462] {standard_task_runner.py:77} INFO - Job 1410: Subtask ingest
[2022-04-13 22:21:39,571] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDAG.ingest manual__2022-04-13T21:15:36.839665+00:00 [running]> on host 13db72185839
[2022-04-13 22:21:39,662] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDAG
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-04-13T21:15:36.839665+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-13T21:15:36.839665+00:00
[2022-04-13 22:21:39,664] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-13 22:21:39,665] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ls /opt/***']
[2022-04-13 22:21:39,678] {subprocess.py:85} INFO - Output:
[2022-04-13 22:21:39,683] {subprocess.py:89} INFO - ***.cfg
[2022-04-13 22:21:39,684] {subprocess.py:89} INFO - dags
[2022-04-13 22:21:39,684] {subprocess.py:89} INFO - logs
[2022-04-13 22:21:39,685] {subprocess.py:89} INFO - output.csv
[2022-04-13 22:21:39,685] {subprocess.py:89} INFO - plugins
[2022-04-13 22:21:39,685] {subprocess.py:89} INFO - requirements.txt
[2022-04-13 22:21:39,686] {subprocess.py:89} INFO - scripts
[2022-04-13 22:21:39,687] {subprocess.py:89} INFO - webserver_config.py
[2022-04-13 22:21:39,687] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-13 22:21:39,718] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDAG, task_id=ingest, execution_date=20220413T211536, start_date=20220413T222139, end_date=20220413T222139
[2022-04-13 22:21:39,751] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-13 22:21:39,791] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
